# For authenticity I'm leaving this untouched however all work bar the starter repo is my own doing.
[package]
name = "shell-starter-rust"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"
